// File: varacore/tests/stress_tests.rs
// Additional edge case stress tests generated by hackathon-stress phase.
// Tests gaps not covered by oracle_tests.rs / reputation_tests.rs / registry_tests.rs.
use gtest::{Program, System};
use parity_scale_codec::Encode;

fn init_varacore(sys: &System) -> Program {
    sys.mint_to(42u64, 1_000_000_000_000_000_u128);
    sys.mint_to(100u64, 1_000_000_000_000_000_u128);
    sys.mint_to(101u64, 1_000_000_000_000_000_u128);
    let program = Program::current(sys);
    let init_id = program.send_bytes(42u64, "New".encode());
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&init_id),
        "VaraCore init failed. failed={:?}",
        result.failed
    );
    program
}

fn agent_actor_id(user: u64) -> [u8; 32] {
    let mut id = [0u8; 32];
    id[..8].copy_from_slice(&user.to_le_bytes());
    id
}

// ─────────────── Oracle edge cases ───────────────

/// ST-F1-EDGE-02: source_count=0 → Err("source_count must be >= 1")
#[test]
fn test_update_price_source_count_zero_rejected() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let payload = (
        "Oracle", "UpdatePrice",
        "VARA/USD",
        100_000_000u128, // valid non-zero price
        0u128,
        1_716_400_000u64,
        0u32, // source_count = 0 → should fail
    ).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "UpdatePrice(source_count=0) panicked — should return Err not panic. failed={:?}",
        result.failed
    );
}

/// ST-F1-EDGE-05: source_count=1 → status=Degraded but Ok(())
#[test]
fn test_update_price_source_count_one_returns_degraded() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let payload = (
        "Oracle", "UpdatePrice",
        "ETH/USD",
        200_000_000_000u128, // $2000 in 8dp
        5_000_000_000u128,
        1_716_400_000u64,
        1u32, // single source → Degraded status
    ).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "UpdatePrice(source_count=1) failed. failed={:?}",
        result.failed
    );
    // Follow up with GetPrice — message should succeed
    let get_payload = ("Oracle", "GetPrice", "ETH/USD").encode();
    let msg_id2 = program.send_bytes(42u64, get_payload);
    let result2 = sys.run_next_block();
    assert!(
        result2.succeed.contains(&msg_id2),
        "GetPrice after Degraded update failed. failed={:?}",
        result2.failed
    );
}

/// ST-F1-EDGE-06: UpdatePrice with price = u128::MAX — should not overflow or panic
#[test]
fn test_update_price_u128_max() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let payload = (
        "Oracle", "UpdatePrice",
        "BTC/USD",
        u128::MAX,
        0u128,
        1_716_400_000u64,
        2u32,
    ).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "UpdatePrice(u128::MAX) panicked — must not overflow. failed={:?}",
        result.failed
    );
}

/// ST-CON-03: TWAP ring buffer wraps correctly after 10 updates (ring size = 8)
#[test]
fn test_twap_ring_buffer_wraps_at_eight() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    for i in 0u64..10 {
        let price = 100_000_000u128 + (i as u128 * 1_000_000u128);
        let payload = (
            "Oracle", "UpdatePrice",
            "DOT/USD",
            price,
            1_000_000u128,
            1_716_400_000u64 + i,
            3u32,
        ).encode();
        let msg_id = program.send_bytes(42u64, payload);
        let result = sys.run_next_block();
        assert!(
            result.succeed.contains(&msg_id),
            "UpdatePrice iteration {} panicked. failed={:?}", i, result.failed
        );
    }
    // GetPrice after 10 updates — should still return a valid price (no panic from ring overflow)
    let get_payload = ("Oracle", "GetPrice", "DOT/USD").encode();
    let msg_id = program.send_bytes(42u64, get_payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "GetPrice after 10-update TWAP ring wrap failed. failed={:?}",
        result.failed
    );
}

/// ST-F1-FUNC-04: GetMultiplePrices with mix of valid and unknown assets
#[test]
fn test_get_multiple_prices_mixed() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    // Seed one asset
    program.send_bytes(42u64, (
        "Oracle", "UpdatePrice",
        "VARA/USD",
        64_000u128,
        1_000u128,
        1_716_400_000u64,
        2u32,
    ).encode());
    sys.run_next_block();

    // Query two assets: one seeded, one not
    let assets: Vec<String> = vec!["VARA/USD".to_string(), "UNKNOWN/USD".to_string()];
    let payload = ("Oracle", "GetMultiplePrices", assets).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "GetMultiplePrices mixed assets panicked. failed={:?}",
        result.failed
    );
}

// ─────────────── Reputation edge cases ───────────────

/// ST-F3-EDGE-02: RecordInteraction with 257-char context — succeeds, truncated to 256
#[test]
fn test_record_interaction_long_context_truncated() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let long_context: String = "x".repeat(257);
    let agent_id = [5u8; 32];
    let payload = ("Reputation", "RecordInteraction", agent_id, true, long_context.as_str()).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "RecordInteraction(257-char context) failed. failed={:?}",
        result.failed
    );
    // GetInteractionHistory — the message must succeed (history is non-empty)
    let hist_payload = ("Reputation", "GetInteractionHistory", agent_id, 1u32).encode();
    let msg_id2 = program.send_bytes(42u64, hist_payload);
    let result2 = sys.run_next_block();
    assert!(
        result2.succeed.contains(&msg_id2),
        "GetInteractionHistory after long context failed. failed={:?}",
        result2.failed
    );
}

/// ST-F3-EDGE-03: 51 interactions — history cap = 50, FIFO eviction
#[test]
fn test_interaction_history_capped_at_50() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let agent_id = [6u8; 32];
    for i in 0u32..51 {
        let ctx = alloc::format!("interaction-{}", i);
        let payload = ("Reputation", "RecordInteraction", agent_id, true, ctx.as_str()).encode();
        let msg_id = program.send_bytes(42u64, payload);
        let result = sys.run_next_block();
        assert!(
            result.succeed.contains(&msg_id),
            "RecordInteraction {} failed. failed={:?}", i, result.failed
        );
    }
    // GetInteractionHistory limit=100 — should succeed and return at most 50 records
    let hist_payload = ("Reputation", "GetInteractionHistory", agent_id, 100u32).encode();
    let msg_id = program.send_bytes(42u64, hist_payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "GetInteractionHistory after 51 interactions failed. failed={:?}",
        result.failed
    );
}

/// ST-F3-EDGE-07: ScoreAgent after only failures — score should be low but > 0 (has interactions)
#[test]
fn test_score_agent_all_failures() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let agent_id = [7u8; 32];
    for _ in 0..5 {
        let payload = ("Reputation", "RecordInteraction", agent_id, false, "fail").encode();
        let msg_id = program.send_bytes(42u64, payload);
        let result = sys.run_next_block();
        assert!(
            result.succeed.contains(&msg_id),
            "RecordInteraction(false) failed."
        );
    }
    // ScoreAgent — should succeed and return data (not Err, since interactions were recorded)
    let payload = ("Reputation", "ScoreAgent", agent_id).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "ScoreAgent after all-failure interactions panicked. failed={:?}",
        result.failed
    );
}

/// ST-F3-EDGE-04: GetTopAgents limit=0 — empty result, no panic
#[test]
fn test_get_top_agents_limit_zero() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let payload = ("Reputation", "GetTopAgents", 0u32).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "GetTopAgents(0) panicked. failed={:?}",
        result.failed
    );
}

/// ST-F3-EDGE-05: GetTopAgents limit=1000 — cap 100 applies
#[test]
fn test_get_top_agents_limit_exceeds_cap() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let payload = ("Reputation", "GetTopAgents", 1000u32).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "GetTopAgents(1000) panicked. failed={:?}",
        result.failed
    );
}

// ─────────────── Registry edge cases ───────────────

/// ST-F4-EDGE-01: RegisterAgent empty hub_handle → Err
#[test]
fn test_register_agent_empty_hub_handle() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let payload = (
        "Registry", "RegisterAgent",
        "",               // empty hub_handle → Err
        vec!["oracle"],
        0u8,              // ServiceType::Oracle
        "desc",
        "http://x.com",
    ).encode();
    let msg_id = program.send_bytes(100u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "RegisterAgent(empty hub_handle) panicked — should return Err. failed={:?}",
        result.failed
    );
}

/// ST-F4-EDGE-02: RegisterAgent 21 capabilities → Err
#[test]
fn test_register_agent_too_many_capabilities() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let caps: Vec<&str> = (0..21).map(|i| if i == 0 { "cap0" } else { "capX" }).collect();
    let caps_owned: Vec<String> = caps.iter().map(|s| s.to_string()).collect();
    let payload = (
        "Registry", "RegisterAgent",
        "my-agent",
        caps_owned,
        0u8,
        "desc",
        "http://x.com",
    ).encode();
    let msg_id = program.send_bytes(100u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "RegisterAgent(21 caps) panicked — should return Err. failed={:?}",
        result.failed
    );
}

/// ST-F4-EDGE-09: RegisterAgent description 513 chars → truncated to 512
#[test]
fn test_register_agent_long_description_truncated() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let long_desc: String = "d".repeat(513);
    let payload = (
        "Registry", "RegisterAgent",
        "my-agent",
        vec!["price-feed"],
        0u8,
        long_desc.as_str(),
        "http://x.com",
    ).encode();
    let msg_id = program.send_bytes(100u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "RegisterAgent(513-char desc) failed. failed={:?}",
        result.failed
    );
    // GetAgent — should succeed (was registered)
    let agent_id = agent_actor_id(100);
    let get_payload = ("Registry", "GetAgent", agent_id).encode();
    let msg_id2 = program.send_bytes(42u64, get_payload);
    let result2 = sys.run_next_block();
    assert!(
        result2.succeed.contains(&msg_id2),
        "GetAgent after long-desc register failed. failed={:?}",
        result2.failed
    );
}

/// ST-F4-EDGE-03: HeartbeatAgent wrong caller → Err (SEC-001)
#[test]
fn test_heartbeat_wrong_caller_returns_err() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    // Register agent as user 100
    let reg_payload = (
        "Registry", "RegisterAgent",
        "user100", vec!["oracle"], 0u8, "desc", "http://x.com",
    ).encode();
    program.send_bytes(100u64, reg_payload);
    sys.run_next_block();

    // Alice (user 42) tries to send heartbeat for user 100's actor_id → Err
    let agent_id = agent_actor_id(100);
    let payload = ("Registry", "HeartbeatAgent", agent_id).encode();
    let msg_id = program.send_bytes(42u64, payload); // 42 != 100
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "HeartbeatAgent(wrong caller) panicked — should return Err. failed={:?}",
        result.failed
    );
}

/// ST-F4-EDGE-04: UpdateAgent wrong caller → Err (SEC-001)
#[test]
fn test_update_agent_wrong_caller_returns_err() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    // Register as user 100
    let reg_payload = (
        "Registry", "RegisterAgent",
        "user100", vec!["oracle"], 0u8, "desc", "http://x.com",
    ).encode();
    program.send_bytes(100u64, reg_payload);
    sys.run_next_block();

    // Try to update from user 42 — should Err
    let agent_id = agent_actor_id(100);
    let update_payload = (
        "Registry", "UpdateAgent",
        agent_id,
        Option::<&str>::Some("evil-handle"), // hub_handle override attempt
        Option::<Vec<&str>>::None,
        Option::<&str>::None,
        Option::<&str>::None,
    ).encode();
    let msg_id = program.send_bytes(42u64, update_payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "UpdateAgent(wrong caller) panicked — should return Err. failed={:?}",
        result.failed
    );
}

/// ST-CON-05: Re-register updates capability index — old caps removed, new caps indexed
#[test]
fn test_reregister_updates_capability_index() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    // Register with cap "cap-a"
    let reg1 = (
        "Registry", "RegisterAgent",
        "my-agent", vec!["cap-a"], 0u8, "desc", "http://x.com",
    ).encode();
    program.send_bytes(100u64, reg1);
    sys.run_next_block();

    // Re-register with cap "cap-b" (replaces cap-a)
    let reg2 = (
        "Registry", "RegisterAgent",
        "my-agent-v2", vec!["cap-b"], 0u8, "desc-updated", "http://x.com",
    ).encode();
    let msg_id = program.send_bytes(100u64, reg2);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "Re-register failed. failed={:?}",
        result.failed
    );

    // GetAgentsByCapability("cap-a") — agent should NOT appear (old caps removed from index)
    let q1 = ("Registry", "GetAgentsByCapability", "cap-a").encode();
    let msg_id2 = program.send_bytes(42u64, q1);
    let result2 = sys.run_next_block();
    assert!(
        result2.succeed.contains(&msg_id2),
        "GetAgentsByCapability(cap-a) after re-register panicked. failed={:?}",
        result2.failed
    );

    // GetAgentsByCapability("cap-b") — agent SHOULD appear
    let q2 = ("Registry", "GetAgentsByCapability", "cap-b").encode();
    let msg_id3 = program.send_bytes(42u64, q2);
    let result3 = sys.run_next_block();
    assert!(
        result3.succeed.contains(&msg_id3),
        "GetAgentsByCapability(cap-b) after re-register panicked. failed={:?}",
        result3.failed
    );
}

/// ST-CON-04: Delist removes agent from capability index
#[test]
fn test_delist_removes_from_capability_index() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    // Register with cap "price-feed"
    let reg = (
        "Registry", "RegisterAgent",
        "my-agent", vec!["price-feed"], 0u8, "desc", "http://x.com",
    ).encode();
    program.send_bytes(100u64, reg);
    sys.run_next_block();

    // Delist as user 100
    let agent_id = agent_actor_id(100);
    let delist = ("Registry", "DelistAgent", agent_id).encode();
    let msg_id = program.send_bytes(100u64, delist);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "DelistAgent failed. failed={:?}",
        result.failed
    );

    // GetAgentsByCapability("price-feed") — should return empty (agent delisted)
    let q = ("Registry", "GetAgentsByCapability", "price-feed").encode();
    let msg_id2 = program.send_bytes(42u64, q);
    let result2 = sys.run_next_block();
    assert!(
        result2.succeed.contains(&msg_id2),
        "GetAgentsByCapability after delist panicked. failed={:?}",
        result2.failed
    );
}

/// ST-CON-06: 2 agents same capability — both returned
#[test]
fn test_two_agents_same_capability_both_returned() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let reg_a = (
        "Registry", "RegisterAgent",
        "agent-a", vec!["shared-cap"], 0u8, "a", "http://a.com",
    ).encode();
    program.send_bytes(100u64, reg_a);
    sys.run_next_block();

    let reg_b = (
        "Registry", "RegisterAgent",
        "agent-b", vec!["shared-cap"], 0u8, "b", "http://b.com",
    ).encode();
    program.send_bytes(101u64, reg_b);
    sys.run_next_block();

    let q = ("Registry", "GetAgentsByCapability", "shared-cap").encode();
    let msg_id = program.send_bytes(42u64, q);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "GetAgentsByCapability(shared-cap) with 2 agents panicked. failed={:?}",
        result.failed
    );
}

/// ST-F4-EDGE-06: GetAgent unregistered actor → Err
#[test]
fn test_get_agent_unregistered_returns_err() {
    let sys = System::new();
    sys.init_logger();
    let program = init_varacore(&sys);

    let unknown_id = [0xabu8; 32];
    let payload = ("Registry", "GetAgent", unknown_id).encode();
    let msg_id = program.send_bytes(42u64, payload);
    let result = sys.run_next_block();
    assert!(
        result.succeed.contains(&msg_id),
        "GetAgent(unregistered) panicked — should return Err. failed={:?}",
        result.failed
    );
}

extern crate alloc;
